"""add cancel_requested to investigations

Revision ID: 26778e03af6d
Revises: 43898bd97590
Create Date: 2026-09-03 21:17:41.270622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26778e03af6d'
down_revision: Union[str, Sequence[str], None] = '43898bd97590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'investigations',
        sa.Column(
            'cancel_requested', sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigations', 'cancel_requested')
    # ### end Alembic commands ###
