"""drop unenforceable products category fk

Revision ID: 3eeb9b6c77e1
Revises: 877d57fcae45
Create Date: 2026-09-03 16:19:33.817910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eeb9b6c77e1'
down_revision: Union[str, Sequence[str], None] = '877d57fcae45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_product_category_name_fkey'), 'products', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('products_product_category_name_fkey'), 'products', 'product_category_translations', ['product_category_name'], ['product_category_name'])
    # ### end Alembic commands ###
