"""add investigation tables

Revision ID: 5fa63c4a2a9a
Revises: 8a6cf99568f8
Create Date: 2026-09-02 23:22:15.133901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fa63c4a2a9a'
down_revision: Union[str, Sequence[str], None] = '8a6cf99568f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('investigation_id', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('metric_definition_version', sa.String(), nullable=False),
    sa.Column('current_period_start', sa.Date(), nullable=False),
    sa.Column('current_period_end', sa.Date(), nullable=False),
    sa.Column('comparison_period_start', sa.Date(), nullable=False),
    sa.Column('comparison_period_end', sa.Date(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('investigation_id')
    )
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('supporting_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contradicting_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_investigation_id'), 'hypotheses', ['investigation_id'], unique=False)
    op.create_table('investigation_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_events_created_at'), 'investigation_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_investigation_events_investigation_id'), 'investigation_events', ['investigation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_events_investigation_id'), table_name='investigation_events')
    op.drop_index(op.f('ix_investigation_events_created_at'), table_name='investigation_events')
    op.drop_table('investigation_events')
    op.drop_index(op.f('ix_hypotheses_investigation_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_table('investigations')
    # ### end Alembic commands ###
