"""create business tables

Revision ID: 8a6cf99568f8
Revises: 
Create Date: 2026-09-02 11:05:27.190901

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8a6cf99568f8'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('customer_unique_id', sa.String(), nullable=False),
    sa.Column('customer_zip_code_prefix', sa.String(), nullable=False),
    sa.Column('customer_city', sa.String(), nullable=False),
    sa.Column('customer_state', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_customer_state'), 'customers', ['customer_state'], unique=False)
    op.create_index(op.f('ix_customers_customer_unique_id'), 'customers', ['customer_unique_id'], unique=False)
    op.create_table('product_category_translations',
    sa.Column('product_category_name', sa.String(), nullable=False),
    sa.Column('product_category_name_english', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('product_category_name')
    )
    op.create_table('sellers',
    sa.Column('seller_id', sa.String(), nullable=False),
    sa.Column('seller_zip_code_prefix', sa.String(), nullable=False),
    sa.Column('seller_city', sa.String(), nullable=False),
    sa.Column('seller_state', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('seller_id')
    )
    op.create_index(op.f('ix_sellers_seller_state'), 'sellers', ['seller_state'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=False),
    sa.Column('order_purchase_timestamp', sa.DateTime(), nullable=False),
    sa.Column('order_approved_at', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_carrier_date', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_customer_date', sa.DateTime(), nullable=True),
    sa.Column('order_estimated_delivery_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_order_purchase_timestamp'), 'orders', ['order_purchase_timestamp'], unique=False)
    op.create_index(op.f('ix_orders_order_status'), 'orders', ['order_status'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_category_name', sa.String(), nullable=True),
    sa.Column('product_weight_g', sa.Integer(), nullable=True),
    sa.Column('product_length_cm', sa.Integer(), nullable=True),
    sa.Column('product_height_cm', sa.Integer(), nullable=True),
    sa.Column('product_width_cm', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_category_name'], ['product_category_translations.product_category_name'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_product_category_name'), 'products', ['product_category_name'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('seller_id', sa.String(), nullable=False),
    sa.Column('shipping_limit_date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('freight_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.seller_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'order_item_id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_items_seller_id'), 'order_items', ['seller_id'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('payment_sequential', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(), nullable=False),
    sa.Column('payment_installments', sa.Integer(), nullable=False),
    sa.Column('payment_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'payment_sequential')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('review_score', sa.Integer(), nullable=False),
    sa.Column('review_creation_date', sa.DateTime(), nullable=False),
    sa.Column('review_answer_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_reviews_order_id'), 'reviews', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_order_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_seller_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_products_product_category_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_order_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_purchase_timestamp'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_sellers_seller_state'), table_name='sellers')
    op.drop_table('sellers')
    op.drop_table('product_category_translations')
    op.drop_index(op.f('ix_customers_customer_unique_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_state'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
